### ISSUE TITLE
add jagwar twin songs

### ISSUE THREAD

**Issue by puffo** [spinamp/spindexer#59]
1 song (hedstape may be an applicable comparison)

 - https://opensea.io/collection/jagwar-twin-thought-forms
55 Sec Interlude / Track:
https://opensea.io/assets/ethereum/0x605b0e6b2ec949235ff5ac05bd452e22d21c702d/1

---

Various Tracks & Interludes  in the NFT collection
 - https://opensea.io/collection/jagwar-twin-33-artifacts (a few of the nfts are actual songs)

Tracks:
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/60
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/14
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/109
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/12
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/2
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/4
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/6

Intro / Interludes:
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/3
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/17
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/1
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/36 (1:56)
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/5 (0:06)

Voice memo (Bonus?):
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/73

Unreleased / Unavailable:
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/123
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/132
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/133
https://opensea.io/assets/ethereum/0x84f89f7bacb20970073be33f22847e58fbe78992/134

 
---
Multi track, multi print of 6 songs
 - https://opensea.io/collection/jagwar-twin-33-album

It's Your Time (02/10)
Online (01/10)
Pay Attention (03/10)
Happy Face (06/10)
Soul is a Star (05/10)
I Like to Party (04/10)

**Comment by puffo** [comment]
Twin Thought Forms is one track/interlude 55 seconds long. 

I imagine I'll just construct a NftFactory with a typeMetadata override? similar to src/db/migrations/08-add-rohki-desperado.ts 

33 Artifacts is a jumbled mix of NFTs but I've listed out the Tracks, Interludes, Bonus track (?), and unreleased content.

1. Seeing as these are pretty specific, should I take a similar approach and just manually craft NftFactory's ?
2. I'm not sure how to manage the unreleased content
3. Do we want to include the 6 second track? I feel like these make sense in the context of an album but might be out of place without some kind of ordering in Spinamp.

Album? looks like a straightforward Multitrack Multiprint, so I'm imagining that the Glasshouse import would be most similar, src/db/migrations/11-add-daniel-allan-glasshouse.ts

I also think some of the upcoming platformIdForPlatformType overrides would probably be helluva useful here to avoid bloating the platforms definitions.

**Comment by musnit** [comment]
One NFTFactory per contract makes sense, yeah!

It does look like each of the 3 above NFTFactory examples are quite different types. At the moment we assume that all NFTFactorys on a given platform can work with the same type mapper, so the above breaks this assumption. This is similar to the issue we have with the new open heds PR (https://github.com/spinamp/spindexer/pull/57) where the latest release is not just a single track on the contract but has many tracks on the contract, and so with heds too we now have multiple different contract types on the same platform.

Using manual typeMetadata overrides is an one way to deal with this - typeMetadata overrides will override fields across all nfts that come from a particular NftFactory. But, it does seem like at this point it makes sense for us to be able to override the type at the  NftFactory level, so that we can support different NftFactory types across a single platform without resorting to lower-level typeMetadata overrides.

We're trying this already in the related heds PR (https://github.com/spinamp/spindexer/pull/57/files#r957847946). I'm actually looking at that now too, so will try review/finalize a way to do this that we merge in and use here.

Also in general some other things to keep in mind, that we'll hopefully get to in time:
 - We def need to write up a doc/guideline that describes how we think about indexing and all these kinda implicit requirements we have to make it easier and more standardized to index stuff in future. We do have the Ingestion.md doc but it's pretty outdated now.
 - Ideally I imagine we want to flesh out the existing extraction system to be a bit more powerful and dynamic. It already allows for this kind of manual, cascading overriding, but making it more general-purpose mechanism to allow for overrides at any level of the stack that cascade down.

Anyway, lets assume we can do NftFactory type overrides, and so to answer with something more concrete, i'll go through it myself and document the process to give a clearer sense of how I'd go about it:

Twin Thought Forms: 
 - looks like the type is just 1 contract with a single song, so the single-track-multiprint-contract type should work fine. This already gets the animation_url, image, external_url (which are fairly commonly seen in nfts and somewhat standardized) so we won't need anything manual extra for those.
 - we'll probably just need to override the artist-related fields
 - for artist id, in general we try use their ethereum address. in this case, you can see on etherscan (https://etherscan.io/address/0x605b0e6b2ec949235ff5ac05bd452e22d21c702d) that the contract was deployed by jagwartwin.eth with address 0xe80c7fee3d41e311e0351244231919e04e699e56, so we can use this 0xe80.. address for the artist id and platform id

Album:
 - yep straightforward as you say. probably need artist overrides like in glass house as you suggest too

33 Artifacts:
 - I do think we should make sure we stick to a single NftFactory for this, rather than multiple, since all nfts are being generated by a single ERC721 ethereum contract and our conceptual model in other processors does assume that a single ERC721 nft contract is represented by a single NftFactory.
 - So digging into what type is best for this album and whether it will work or not, let's consider all the usual things and fields we need for a track:
    - baseline analysis: yep, as you say it looks like a mix of things - multiple tracks across different nfts. at a first guess, the multi-track-multiprint-contract type is the most general and so let's see if we can use that.
    - audio: Looks like metadata.animation_url is fine for this on the songs, so we won't need any nft-level override. The multi-track-multiprint-contract type also already uses this as a default (https://github.com/spinamp/spindexer/blob/main/src/types/platforms-types/multi-track-multiprint-contract.ts#L28). While looking at that, I do notice this actually assumes that the field contains an IPFS hash, which is not always generally the case, but seems to be a correct assumption for 33 Artifacts. This should work, but I would suggest we (a) create a github issue to improve the robustness of the multi-track-multiprint-contract type to have a fallback such that if it does not detect an ipfs url, it puts that url into the lossyAudioURL field so that the later ipfs uploader processor will detect this and upload the file to ipfs to fill in that field later
     - image field: Looks like songs don't have their own image, so i guess a NftFactory-wide, manual typeOverride for this, that uses the album's image is appropriate and needed.
      - track name: looks like metadata.name is fine for this. It looks like the multi-track-multiprint-contract type defaults to getting the name from a trait field in the metadata (https://github.com/spinamp/spindexer/blob/main/src/types/platforms-types/multi-track-multiprint-contract.ts#L25), so it won't get the name correctly. We could add a secondary default fallback to metadata.name, which we do have on this album and which is very common too, but many nfts will put an nft-specific name rather than a track-specific name here (eg: in some contracts where there are 10 prints/nfts for a single track, the name might be something like TrackName #1 and TrackName #2), so using metadata.name as a general default could be problematic. Ideally we want to use metadata.name as the field to extract a track name from just for this album. Our existing typeOverride allows us to override the name across all nfts, but in this case we don't want to override the name itself, we actually want to override the extraction method for just the name field so that is uses metadata.name. I've actually wanted to implement a way for us to be able to override the extraction method at a lower level on a field-specific basis, rather than just with NftFactory types, so this could be an opportunity to quickly implement an experimental version of this. See (b) below for a suggestion here.
    - distinguishing potentially duplicate tracks: it doesn't seem like this is an issue here, since the contract only has 1 of 1 songs, no duplicates
    - artist: a global typeOverride as in the others should be fine
    - distinguishing audio from non-audio: We don't yet have an automated way to do this. I do imagine we'll get to this in future by writing a processor that checks the file contents to detect the type of content, but we do have a way to do this via manual approvals. The easiest thing for now I think is for us to set the NftFactory to have autoApprove false and then just approve the nfts we want to
     - distinguishing audio we want from audio we don't want: As above, using the approval mechanism should work. Since we don't really have a way to cohesively present albums or projects like this in Spinamp in the app yet anyway, we won't really be able to present interludes/memos in a clean way. I think for now lets just approve them all and let them go in nonetheless.
     - handling unreleased content: We can just not approve them yet for now. This will mean that if they are released in future, we won't have a way to automatically detect and release them and will need to manually approve again. Also not ideal, but I think fine for now. Once we implement the typeDetector processor then we'll be able to automate this kind of thing more easily in future.

Concrete tasks/outcomes:
 - (a) create a github issue to improve the robustness of the multi-track-multiprint-contract type to have a fallback such that if it does not detect an ipfs url, it puts that url into the lossyAudioURL field so that the later ipfs uploader processor will detect this and upload the file to ipfs to fill in that field later
 - (b) Implement a way to allow type-overrides at a field level. I think this task could involve a more robust long term scalable design, but for this release maybe we should just do a scrappy experiment so we can ship quickly, and we can generalize it later? I'd suggest something like the following:

```
// in nft.ts

export const fieldExtractors = {
  'metadata.name': (nft) => nft.metadata.name
}

// in the the jagwar-twin.ts migration in the 33-artifacts nftFactory insert:
  typeMetadata: {
    extractorOverrides: {
       title: 'metadata.name'
    }
  }

// in multi-track-multiprint-contract.ts
 const defaultTitleExtractor = nft => getTrait(nft, 'Track');
 const titleExtractorOverride = contract.typeMetadata?.extractorOverrides?.title;
 const titleExtractor = titleExtractorOverride? fieldExtractors[titleExtractorOverride] : defaultTitleExtractor; 

 // and replace this line:
    title: getTrait(nft, 'Track'),

  // with something like:
    title: titleExtractor(nft),
``
